
class Constans:

    CREATE_PRODUCT_NAME = 'f731'
    CREATE_PRODUCT_PRICE = '1000'
    CREATE_PRODUCT_DESCRIPTION = 'description'
    CREATE_PRODUCT_IMAGE = 'image'

    EDIT_PRODUCT_NAME = 'f73.v2'
    EDIT_PRODUCT_PRICE = '2000'
    EDIT_PRODUCT_DESCRIPTION = 'new_description'
    EDIT_PRODUCT_IMAGE = 'new_image'
