version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:latest
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./browsers.json:/etc/selenoid/browsers.json"
    command: [
      "-container-network", "selenoid_net",
      "-timeout", "2m",
      "-service-startup-timeout", "2m"
    ]
    networks:
      - selenoid_net

  tests:
    build: .
    depends_on:
      - selenoid
    environment:
      SELENOID_URL: "http://selenoid:4444/wd/hub"
    networks:
      - selenoid_net
    volumes:
      - "./allure-results:/app/allure-results"

networks:
  selenoid_net:
    driver: bridge
    external: true  # Сеть должна существовать до запуска