version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:latest
    hostname: selenoid
    ports:
      - "4444:4444"
    command: ["-container-network", "avi_qa_lichinin_2025_selenoid_net"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./browsers.json:/etc/selenoid/browsers.json"
    networks:
      - selenoid_net

  tests:
    build: .
    depends_on:
      - selenoid
    environment:
      SELENOID_URL: "http://selenoid:4444/wd/hub"
    volumes:
      - "./allure-results:/app/allure-results"
    networks:
      - selenoid_net

networks:
  selenoid_net:
    driver: bridge